import { after, before, test } from 'node:test'
import assert from 'node:assert/strict'
import { captureText, signedIn, startStack } from './helpers.js'

let stack
before(async () => { stack = await startStack() })
after(async () => { await stack.stop() })

async function billDoc(agent) {
  const { job } = await captureText(stack, agent, 'voice_bill', 'do kilo basmati chawal aur ek litre sarson tel')
  return (await agent.get(`/api/documents/${job.documentId}`)).body
}

test('another workspace cannot see, edit or export your documents', async () => {
  const a = await signedIn(stack)
  const b = await signedIn(stack)
  const doc = await billDoc(a.agent)
  assert.equal((await b.agent.get(`/api/documents/${doc.id}`)).status, 404)
  assert.equal((await b.agent.patch(`/api/documents/${doc.id}`).send({ title: 'mine now' })).status, 404)
  assert.equal((await b.agent.get(`/api/documents/${doc.id}/export?format=pdf`)).status, 404)
  assert.equal((await b.agent.get(`/api/jobs/${doc.jobId}`)).status, 404)
  const bList = (await b.agent.get('/api/documents')).body
  assert.ok(!bList.some((d) => d.id === doc.id))
})

test('edits create versions; a stale version is refused', async () => {
  const { agent } = await signedIn(stack)
  const doc = await billDoc(agent)
  const v2 = await agent.patch(`/api/documents/${doc.id}`).send({ title: 'Counter bill', content: { ...doc.content, customer: 'Sharma ji' }, expectedVersion: 1 })
  assert.equal(v2.status, 200)
  assert.equal(v2.body.version, 2)
  assert.equal(v2.body.content.customer, 'Sharma ji')
  const stale = await agent.patch(`/api/documents/${doc.id}`).send({ title: 'Other', expectedVersion: 1 })
  assert.equal(stale.status, 409)
  assert.equal(stale.body.error.code, 'version_conflict')
  const versions = (await agent.get(`/api/documents/${doc.id}/versions`)).body
  assert.deepEqual(versions.map((v) => v.version), [2, 1])
  assert.equal(versions[1].createdBy, null) // v1 was generated by YounifyAI
})

test('approval is blocked by errors and withdrawn by later edits', async () => {
  const { agent } = await signedIn(stack)
  const doc = await billDoc(agent)
  const broken = await agent.patch(`/api/documents/${doc.id}`).send({ content: { ...doc.content, items: [] }, expectedVersion: 1 })
  assert.ok(broken.body.issues.some((i) => i.level === 'error'))
  const blocked = await agent.post(`/api/documents/${doc.id}/approve`)
  assert.equal(blocked.status, 422)

  const fixed = await agent.patch(`/api/documents/${doc.id}`).send({ content: doc.content, expectedVersion: 2 })
  const approved = await agent.post(`/api/documents/${doc.id}/approve`)
  assert.equal(approved.status, 200)
  assert.equal(approved.body.status, 'approved')
  assert.ok(approved.body.approvedBy.name)

  const edited = await agent.patch(`/api/documents/${doc.id}`).send({ title: 'changed', expectedVersion: fixed.body.version })
  assert.equal(edited.body.status, 'draft')
  assert.equal(edited.body.approvedAt, null)
  const trail = (await agent.get(`/api/audit?documentId=${doc.id}`)).body.map((a) => a.action)
  assert.ok(trail.includes('document.approved') && trail.includes('document.edited') && trail.includes('document.generated'))
})

test('restoring a version appends a new one', async () => {
  const { agent } = await signedIn(stack)
  const doc = await billDoc(agent)
  await agent.patch(`/api/documents/${doc.id}`).send({ title: 'Changed title', expectedVersion: 1 })
  const versions = (await agent.get(`/api/documents/${doc.id}/versions`)).body
  const v1 = versions.find((v) => v.version === 1)
  const restored = await agent.post(`/api/documents/${doc.id}/versions/${v1.id}/restore`)
  assert.equal(restored.status, 200)
  assert.equal(restored.body.version, 3)
  assert.equal(restored.body.title, doc.title)
  const after3 = (await agent.get(`/api/documents/${doc.id}/versions`)).body
  assert.equal(after3[0].note, 'Restored v1')
})

test('exports: PDF and Markdown on Free, DOCX and JSON need Premium', async () => {
  const { agent } = await signedIn(stack)
  const doc = await billDoc(agent)
  const pdf = await agent.get(`/api/documents/${doc.id}/export?format=pdf`).buffer(true)
  assert.equal(pdf.status, 200)
  assert.equal(pdf.headers['content-type'], 'application/pdf')
  assert.equal(pdf.body.subarray(0, 5).toString(), '%PDF-')
  assert.match(pdf.headers['content-disposition'], /attachment; filename=".+\.pdf"/)
  const md = await agent.get(`/api/documents/${doc.id}/export?format=md`)
  assert.match(md.text, /\| Item \| Qty \| Unit \| Rate \| Amount \|/)
  assert.equal((await agent.get(`/api/documents/${doc.id}/export?format=docx`)).status, 402)

  await agent.put('/api/workspace/plan').send({ plan: 'premium' })
  const docx = await agent.get(`/api/documents/${doc.id}/export?format=docx`).buffer(true).parse((r, cb) => {
    const chunks = []
    r.on('data', (c) => chunks.push(c))
    r.on('end', () => cb(null, Buffer.concat(chunks)))
  })
  assert.equal(docx.status, 200)
  assert.equal(docx.body.subarray(0, 2).toString(), 'PK')
  const json = await agent.get(`/api/documents/${doc.id}/export?format=json`)
  assert.equal(JSON.parse(json.text).content.total, doc.content.total)
})

test('search finds documents by words in their content', async () => {
  const { agent } = await signedIn(stack)
  await billDoc(agent)
  const hits = (await agent.get('/api/documents?q=mustard')).body
  assert.ok(hits.length >= 1 && hits.every((d) => d.templateId === 'voice_bill'))
  const partial = (await agent.get('/api/documents?q=Thermo')).body
  assert.ok(partial.some((d) => /Thermodynamics/.test(d.title)))
  const none = (await agent.get('/api/documents?q=zebra-crossing-xyz')).body
  assert.equal(none.length, 0)
})

test('deleting a document keeps its audit trail', async () => {
  const { agent } = await signedIn(stack)
  const doc = await billDoc(agent)
  assert.equal((await agent.delete(`/api/documents/${doc.id}`)).status, 204)
  assert.equal((await agent.get(`/api/documents/${doc.id}`)).status, 404)
  const trail = (await agent.get(`/api/audit?documentId=${doc.id}`)).body.map((a) => a.action)
  assert.ok(trail.includes('document.deleted'))
})
