-- YounifyAI core schema.
-- Runs unchanged on PGlite (local) and Supabase / any Postgres 15+ (production).
-- Everything lives in the private `app` schema: Supabase exposes `public` through
-- its REST API by default, and none of these tables should be reachable that way.
--
-- IDs are UUIDv7 generated by the API (time-ordered, so inserts stay index-friendly);
-- gen_random_uuid() is only a fallback default for hand-written SQL.

create schema if not exists app;
create extension if not exists vector;

-- ------------------------------------------------------------------ identity

create table app.users (
  id            uuid primary key default gen_random_uuid(),
  email         text not null,
  name          text not null,
  password_hash text not null,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  constraint users_email_lowercase check (email = lower(email)),
  constraint users_name_present check (length(trim(name)) > 0)
);
create unique index users_email_key on app.users (email);

-- ---------------------------------------------------------------- workspaces

create table app.workspaces (
  id         uuid primary key default gen_random_uuid(),
  name       text not null,
  plan       text not null default 'free',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint workspaces_plan_check check (plan in ('free', 'premium', 'pro'))
);

-- Opaque session tokens. Only the SHA-256 of the token is stored.
-- workspace_id is the workspace the person is currently working in.
create table app.sessions (
  id           uuid primary key default gen_random_uuid(),
  user_id      uuid not null references app.users (id) on delete cascade,
  workspace_id uuid references app.workspaces (id) on delete set null,
  token_hash   text not null,
  user_agent   text,
  ip           text,
  created_at   timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  expires_at   timestamptz not null
);
create unique index sessions_token_hash_key on app.sessions (token_hash);
create index sessions_user_id_idx on app.sessions (user_id);
create index sessions_expires_at_idx on app.sessions (expires_at);
create index sessions_workspace_id_idx on app.sessions (workspace_id);

-- A person's place in a workspace. user_id is null while an invite is pending.
create table app.memberships (
  id           uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references app.workspaces (id) on delete cascade,
  user_id      uuid references app.users (id) on delete cascade,
  email        text not null,
  role         text not null,
  status       text not null default 'active',
  invited_by   uuid references app.users (id) on delete set null,
  created_at   timestamptz not null default now(),
  joined_at    timestamptz,
  constraint memberships_role_check check (role in ('owner', 'editor', 'viewer')),
  constraint memberships_status_check check (status in ('active', 'invited')),
  constraint memberships_active_has_user check (status = 'invited' or user_id is not null)
);
create unique index memberships_workspace_email_key on app.memberships (workspace_id, email);
create index memberships_user_id_idx on app.memberships (user_id);
create index memberships_invited_by_idx on app.memberships (invited_by);

-- ----------------------------------------------------------------- templates

-- System templates (workspace_id is null) are upserted from the shared catalog on boot.
-- Custom templates belong to a workspace. Deleting one sets deleted_at so documents
-- made from it keep their field schema.
create table app.templates (
  id           text primary key,
  workspace_id uuid references app.workspaces (id) on delete cascade,
  name         text not null,
  description  text not null default '',
  instructions text not null default '',
  vertical     text not null default 'Custom',
  stage        text not null default 'custom',
  flow         text not null default '',
  accepts      text[] not null,
  fields       jsonb not null,
  created_by   uuid references app.users (id) on delete set null,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  deleted_at   timestamptz,
  constraint templates_fields_is_array check (jsonb_typeof(fields) = 'array'),
  constraint templates_stage_check check (stage in ('mvp', 'expansion', 'custom'))
);
create index templates_workspace_id_idx on app.templates (workspace_id) where deleted_at is null;
create index templates_created_by_idx on app.templates (created_by);

-- ---------------------------------------------------------------- knowledge

create table app.sources (
  id           uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references app.workspaces (id) on delete cascade,
  template_id  text references app.templates (id) on delete set null,
  title        text not null,
  kind         text not null,
  mime         text,
  storage_key  text,
  text_content text not null,
  chars        integer generated always as (length(text_content)) stored,
  created_by   uuid references app.users (id) on delete set null,
  created_at   timestamptz not null default now(),
  constraint sources_kind_check check (kind in ('text', 'file'))
);
create index sources_workspace_id_idx on app.sources (workspace_id, created_at desc);
create index sources_template_id_idx on app.sources (template_id);
create index sources_created_by_idx on app.sources (created_by);

-- Chunks of reference text with embeddings for the Retrieve stage.
-- 384 dimensions matches the local embedder and all-MiniLM-L6-v2.
create table app.source_chunks (
  id           bigint generated always as identity primary key,
  source_id    uuid not null references app.sources (id) on delete cascade,
  workspace_id uuid not null references app.workspaces (id) on delete cascade,
  position     integer not null,
  content      text not null,
  embedding    vector(384),
  embed_model  text  -- vectors from different embedders are never compared
);
create index source_chunks_source_id_idx on app.source_chunks (source_id);
create index source_chunks_workspace_id_idx on app.source_chunks (workspace_id);

-- --------------------------------------------------------------------- jobs

-- One capture = one job = one document. Workers claim queued jobs with
-- FOR UPDATE SKIP LOCKED, so any number of them can run side by side.
create table app.jobs (
  id           uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references app.workspaces (id) on delete cascade,
  template_id  text not null references app.templates (id),
  created_by   uuid references app.users (id) on delete set null,
  status       text not null default 'queued',
  instructions text not null default '',
  attempts     smallint not null default 0,
  error        text,
  document_id  uuid,
  locked_by    text,
  locked_at    timestamptz,
  created_at   timestamptz not null default now(),
  started_at   timestamptz,
  finished_at  timestamptz,
  constraint jobs_status_check check (status in ('queued', 'running', 'succeeded', 'failed'))
);
create index jobs_workspace_created_idx on app.jobs (workspace_id, created_at desc);
create index jobs_queue_idx on app.jobs (created_at) where status = 'queued';
create index jobs_running_idx on app.jobs (locked_at) where status = 'running';
create index jobs_template_id_idx on app.jobs (template_id);
create index jobs_created_by_idx on app.jobs (created_by);

create table app.job_inputs (
  id             uuid primary key default gen_random_uuid(),
  job_id         uuid not null references app.jobs (id) on delete cascade,
  workspace_id   uuid not null references app.workspaces (id) on delete cascade,
  position       smallint not null,
  kind           text not null,
  name           text not null,
  mime           text,
  size_bytes     bigint not null default 0,
  storage_key    text,
  text_content   text,
  extracted_text text,
  meta           jsonb not null default '{}',
  created_at     timestamptz not null default now(),
  constraint job_inputs_kind_check check (kind in ('voice', 'video', 'image', 'text', 'docs')),
  constraint job_inputs_has_payload check (storage_key is not null or text_content is not null)
);
create index job_inputs_job_id_idx on app.job_inputs (job_id, position);
create index job_inputs_workspace_id_idx on app.job_inputs (workspace_id);

create table app.job_stages (
  job_id       uuid not null references app.jobs (id) on delete cascade,
  workspace_id uuid not null references app.workspaces (id) on delete cascade,
  stage        text not null,
  position     smallint not null,
  status       text not null default 'pending',
  log          jsonb not null default '[]',
  started_at   timestamptz,
  finished_at  timestamptz,
  primary key (job_id, stage),
  constraint job_stages_stage_check check (stage in ('capture', 'extract', 'normalize', 'retrieve', 'generate', 'validate', 'deliver')),
  constraint job_stages_status_check check (status in ('pending', 'running', 'done', 'failed', 'skipped'))
);
create index job_stages_workspace_id_idx on app.job_stages (workspace_id);

-- ---------------------------------------------------------------- documents

create table app.documents (
  id           uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references app.workspaces (id) on delete cascade,
  template_id  text not null references app.templates (id),
  job_id       uuid references app.jobs (id) on delete set null,
  title        text not null,
  status       text not null default 'draft',
  content      jsonb not null,
  inputs       jsonb not null default '[]',
  version      integer not null default 1,
  is_sample    boolean not null default false,
  engine       text not null default 'offline',
  created_by   uuid references app.users (id) on delete set null,
  approved_by  uuid references app.users (id) on delete set null,
  approved_at  timestamptz,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  search       tsvector generated always as (
    to_tsvector('simple', coalesce(title, '') || ' ' || coalesce(content::text, ''))
  ) stored,
  constraint documents_status_check check (status in ('draft', 'approved')),
  constraint documents_approval_consistent check ((status = 'approved') = (approved_at is not null)),
  constraint documents_content_is_object check (jsonb_typeof(content) = 'object')
);
create index documents_workspace_updated_idx on app.documents (workspace_id, updated_at desc);
create index documents_workspace_status_idx on app.documents (workspace_id, status);
create index documents_template_id_idx on app.documents (template_id);
create index documents_job_id_idx on app.documents (job_id);
create index documents_created_by_idx on app.documents (created_by);
create index documents_approved_by_idx on app.documents (approved_by);
create index documents_search_idx on app.documents using gin (search);

alter table app.jobs
  add constraint jobs_document_id_fkey foreign key (document_id) references app.documents (id) on delete set null;
create index jobs_document_id_idx on app.jobs (document_id);

-- Every saved state of a document. Restoring a version appends a new one.
create table app.document_versions (
  id          uuid primary key default gen_random_uuid(),
  document_id uuid not null references app.documents (id) on delete cascade,
  workspace_id uuid not null references app.workspaces (id) on delete cascade,
  version     integer not null,
  title       text not null,
  content     jsonb not null,
  note        text not null,
  created_by  uuid references app.users (id) on delete set null,
  created_at  timestamptz not null default now()
);
create unique index document_versions_doc_version_key on app.document_versions (document_id, version);
create index document_versions_workspace_id_idx on app.document_versions (workspace_id);
create index document_versions_created_by_idx on app.document_versions (created_by);

-- -------------------------------------------------------------------- audit

-- Append-only. document_id has no foreign key on purpose: the trail outlives
-- the documents it describes.
create table app.audit_events (
  id           bigint generated always as identity primary key,
  workspace_id uuid not null references app.workspaces (id) on delete cascade,
  document_id  uuid,
  actor_id     uuid references app.users (id) on delete set null,
  action       text not null,
  detail       text not null default '',
  meta         jsonb not null default '{}',
  created_at   timestamptz not null default now()
);
create index audit_events_workspace_idx on app.audit_events (workspace_id, created_at desc);
create index audit_events_document_idx on app.audit_events (document_id, created_at desc) where document_id is not null;
create index audit_events_actor_id_idx on app.audit_events (actor_id);
